services:
  app:
    build: .
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - nginx_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://20.244.90.220:3000/"]
      interval: 30s
      retries: 3
      
networks:
  nginx_network:
    external: true

